### ISSUE TITLE
Remove IF in line 531

### ISSUE THREAD

**Issue by sven4all** [dr-jts/pg_svg#8]
I am wondering if the IF in END IF in line 531 https://github.com/dr-jts/pg_svg/blob/master/pg-svg-lib.sql#L531 is really necesarry? On my local machine it works fine, but when I tried to deploy this code it gave problems. When I removed the IF it started working.

**Comment by dr-jts** [comment]
Thanks, that's a bug.  Fixed by https://github.com/dr-jts/pg_svg/commit/c90d13049ea615f297cda3362904a24b81365ec8.
